name: Release
on:
  push:
    tags:
      - '*'
    branches-ignore:
      - '*'

jobs:
  release:
    runs-on: macos-11.0
    steps:
      - name: Granting private modules access
        run: |
          git config --global url."https://${{ secrets.GO_MODULES_TOKEN }}:x-oauth-basic@github.com/blacs30".insteadOf "https://github.com/blacs30"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16beta1

      - name: Check out code
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      -
        name: "Validates GO releaser config"
        uses: goreleaser/goreleaser-action@v2
        with:
          args: check

      - name: Build Alfred workflow
        run: |
          go get -u github.com/jason0x43/go-alfred/alfred
          go mod download
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o $(pwd)/workflow/bitwarden-alfred-workflow-amd64 .
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o $(pwd)/workflow/bitwarden-alfred-workflow-arm64 .
          lipo -create -output $(pwd)/workflow/bitwarden-alfred-workflow $(pwd)/workflow/bitwarden-alfred-workflow-amd64 $(pwd)/workflow/bitwarden-alfred-workflow-arm64
          rm -f $(pwd)/workflow/bitwarden-alfred-workflow-amd64
          rm -f $(pwd)/workflow/bitwarden-alfred-workflow-arm64

      - name: Copy run dependencies
        run: |
          cp -r icons ./workflow
          cp -r assets ./workflow
          go get github.com/pschlump/markdown-cli
          markdown-cli -i README.md -o workflow/README.html

      - name: Package Alfred workflow
        run: |
          cd ./workflow && zip -r ../bitwarden-alfred-workflow.alfredworkflow ./*
          cd .. && rm -rf workflow && git checkout workflow

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
